#ifndef ECS_TYPES_H
#define ECS_TYPES_H

typedef enum{
  ENTITY_PLAYER = 0,
  ENTITY_ENEMY_SCOUT,
  ENTITY_ENEMY_FIGHTER,
  ENTITY_COUNT
} EntityType;

typedef enum{
  WEAPON_PULSE_LASER = 0,
  WEAPON_LASER_BEAM,
  WEAPON_MACHINE_GUN,
  WEAPON_COUNTER
} WeaponType;

typedef enum{
  AIM_MODE_PHYSICAL = 0,
  AIM_MODE_CAMERA,
} AimMode;

typedef enum{
  EFFECT_NONE = 0,
  EFFECT_SMALL_SPARK,
  EFFECT_MEDIUM_EXPLOSION,
  EFFECT_BIG_BOOM,
  EFFECT_COUNTER
} Effect;

#endif
