#ifndef ECS_TYPES_H
#define ECS_TYPES_H

typedef enum{
  ENTITY_PLAYER = 0,
  ENTITY_ENEMY_SCOUT,
  ENTITY_ENEMY_FIGHTER,
  ENTITY_COUNT
} EntityType;

typedef enum{
  WEAPON_TYPE_NONE = 0,
  WEAPON_PULSE_LASER,
  WEAPON_LASER_BEAM,
  WEAPON_MISSILE_LAUNCHER,
  WEAPON_MACHINE_GUN,
  WEAPON_COUNTER
} WeaponType;

typedef enum{
  AIM_MODE_PHYSICAL = 0,
  AIM_MODE_CAMERA,
} AimMode;

typedef enum{
  FX_TYPE_SPRITESHEET = 0,
  FX_TYPE_ARRAY,
  FX_TYPE_STATIC,
} EffectRenderType;

#endif
